### ISSUE TITLE
Add missing SECURITY Responsible Disclosure Policy

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/preview#12]
The SECURITY.md file is missing. Example: https://github.com/NodeSecure/scanner/blob/master/SECURITY.md

Also we should add badges at the top of the README:
![image](https://user-images.githubusercontent.com/4438263/147836613-746211a3-277d-4479-883c-9817efb0c617.png)

**Comment by viterb-c** [comment]
Hello 👋  , 

Some quick questions : 
- should we use the same SECURITY.md file ? 
- what is the version of the project ? 1.0.0 ? 
- what is the license ? MIT ? 

Thank you

**Comment by fraxken** [comment]
Hello @viterb-c 

Yes this is the same SECURITY.md file. Yes i think 1.0.0 is ok and MIT too.

@tony-go ok the version ?

**Comment by tony-go** [comment]
Okay for the version ^^
