### ISSUE TITLE
feat(ui): add a "powered by NodeSecure" footer

### ISSUE THREAD

**Issue by tony-go** [NodeSecure/preview#3]
Preview 🕸 aims to help newcomers to adopt NodeSecure without installing it.

Once the user came to the website and makes an analysis, then we should invite him to install NodeSecure.

The footer should contain:
- "Powered by NodeSecure" label
- The official logo
- Link to the organization (current nsecure from ES-Community)
- In the `Layout` component

**Comment by MehdiHan** [comment]
Hope my PR will help you #8. 
Feel free to ask me if you want to improve this.

**Comment by tony-go** [comment]
Thanks a lot for the job ^^
